name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install frontend dependencies
      run: npm ci
      
    - name: Install backend dependencies
      run: |
        cd server
        npm ci
        
    - name: Run frontend tests
      run: npm run test --if-present
      
    - name: Run backend tests
      run: |
        cd server
        npm run test --if-present
        
    - name: Test enhanced form layout
      run: |
        echo "Testing enhanced 95% width form layout compatibility..."
        # Add specific tests for form layout if needed
        
    - name: Validate release notes
      run: |
        echo "Validating release notes..."
        if [ -f "RELEASE_NOTES.md" ]; then
          echo "✅ RELEASE_NOTES.md exists"
          if grep -q "Version.*Enhanced Form Layout" RELEASE_NOTES.md; then
            echo "✅ Release notes contain form layout information"
          else
            echo "⚠️ Release notes may be missing form layout details"
          fi
        else
          echo "⚠️ RELEASE_NOTES.md not found"
        fi
        
    - name: Build frontend
      run: npm run build
      
    - name: Build backend
      run: |
        cd server
        npm run build --if-present

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint --if-present
      
    - name: Run TypeScript check
      run: npx tsc --noEmit
      
    - name: Validate changelog
      run: |
        echo "Validating CHANGELOG.md format..."
        if [ -f "CHANGELOG.md" ]; then
          echo "✅ CHANGELOG.md exists"
          # Check for required sections
          if grep -q "## \[Unreleased\]" CHANGELOG.md; then
            echo "✅ Unreleased section found"
          else
            echo "❌ Unreleased section missing"
            exit 1
          fi
        else
          echo "❌ CHANGELOG.md not found"
          exit 1
        fi

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      
    - name: Run backend security audit
      run: |
        cd server
        npm audit --audit-level moderate

  deploy:
    needs: [test, lint, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add your deployment commands here
        
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        echo "Testing enhanced form layout deployment..."
        # Add your smoke test commands here
